// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7qYv9iWqzg0ydM_NpYlXZK0CAkDrkkaU',
    appId: '1:251019245440:android:56a46c68a8668f1a7e3365',
    messagingSenderId: '251019245440',
    projectId: 'messenger-app-acf75',
    storageBucket: 'messenger-app-acf75.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKe0p306ccsZ-EMWzM2WE0Uqf1LO8Qn4M',
    appId: '1:251019245440:web:dca3b70992bbbe047e3365',
    messagingSenderId: '251019245440',
    projectId: 'messenger-app-acf75',
    authDomain: 'messenger-app-acf75.firebaseapp.com',
    storageBucket: 'messenger-app-acf75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuPVCwPzIT9eHWvj4WHMNLgOg_hARTTsI',
    appId: '1:251019245440:ios:ebca9c3e8c93a1687e3365',
    messagingSenderId: '251019245440',
    projectId: 'messenger-app-acf75',
    storageBucket: 'messenger-app-acf75.firebasestorage.app',
    iosBundleId: 'com.example.messagenerApp',
  );

}